title: Where I make stuff
author: Thomas K.
email: thomassth@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Making upp stuff as I go.
  Learning codes left and right.
  Building small things, helping others.
# social links
twitter_username: thomassumthing
github_username:  thomassth

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
